In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(100))

In [4]:
%timeit my_arr2 = my_arr *2

2.93 ms ± 372 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

4.66 μs ± 2.54 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
print(my_arr)

In [16]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


### 4.1 다차원 배열 객체 ndarray
- 넘파이는 대규모 데이터셋을 담을 수 있는 빠르고 유연한 자료 구조다.

In [18]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [19]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [20]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [22]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [23]:
data.shape

(2, 3)

In [24]:
data.dtype

dtype('float64')

#### 4.1.1 ndarray 생성하기

In [29]:
data1 = [6, 7.5, 8, 0, 1]

In [30]:
arr1 = np.array(data1)

In [31]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [32]:
data1

[6, 7.5, 8, 0, 1]

- 리스트 길이가 동일한 중첩된 순차 데이터는 다차원 배열로 변환 가능하다

In [33]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [35]:
arr2 = np.array(data2)

In [36]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- data2는 리스트를 담고 있는 리스트이므로 넘파이 배열인 arr2는 해당 데이터로부터 형태를 추론해 2차원 형태로 생성된다.

In [37]:
arr2.ndim

2

In [38]:
arr2.shape

(2, 4)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
arr2.dtype

dtype('int64')