In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(100))

In [4]:
%timeit my_arr2 = my_arr *2

3.41 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

3.81 μs ± 238 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [7]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


### 4.1 다차원 배열 객체 ndarray
- 넘파이는 대규모 데이터셋을 담을 수 있는 빠르고 유연한 자료 구조다.

In [8]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [9]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [10]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

#### 4.1.1 ndarray 생성하기

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data1

[6, 7.5, 8, 0, 1]

- 리스트 길이가 동일한 중첩된 순차 데이터는 다차원 배열로 변환 가능하다

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr2 = np.array(data2)

In [20]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- data2는 리스트를 담고 있는 리스트이므로 넘파이 배열인 arr2는 해당 데이터로부터 형태를 추론해 2차원 형태로 생성된다.

In [21]:
arr2.ndim

2

In [22]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int64')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [29]:
arr1.dtype
arr2.dtype

print(arr1, arr2)

[1. 2. 3.] [1 2 3]


In [30]:
arr = np.array([1,2,3,4,5])

In [31]:
arr.dtype 

dtype('int64')

In [32]:
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

[1. 2. 3. 4. 5.]
float64


#### 숫자 형식의 문자열을 담고 있는 배열이 있다면 'astype'을 사용해 숫자로 변환할 수 있다.

In [33]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)

In [34]:
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

In [35]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [36]:
arr = np.array([[1,2,3], [4,5,6]])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [39]:
arr = [[1, 2, 3], [4, 5, 6]]
total_sum = 0

for row in arr:
    for element in row:
        total_sum += element

print("Total Sum:", total_sum)

Total Sum: 21


In [40]:
arr = [[1, 2, 3], [4, 5, 6]]
result = []

for row in arr:
    new_row = []
    for element in row:
        new_row.append(element * 2)
    result.append(new_row)

print("Result after multiplying by 2:", result)


Result after multiplying by 2: [[2, 4, 6], [8, 10, 12]]


#### 4.1.3 넘파이 배열의 산술 연산

In [43]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [44]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 4.1.4 색인과 슬라이싱 기초

In [45]:
arr = np.arange(10)

In [47]:
print([arr[5], arr[5:8]])

[np.int64(5), array([5, 6, 7])]


In [48]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr_slice = arr[5:8]

In [50]:
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345

In [52]:
arr_slice

array([   12, 12345,    12])

In [56]:
arr_copy = arr[5:8].copy()

In [57]:
arr_copy

array([   12, 12345,    12])