# Tensor
Tensor는 multi-dimensional array를 나타내는 말로, TensorFlow의 기본 data type이다.

In [8]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
# hello world
hello = tf.constant([3,3], dtype = tf.float32)
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)


In [4]:
# 상수형 tensor는 아래와 같이 만들 수 있다.
# 출력하면 tensor의 값과 함께, shape와 내부의 data type을 함께 볼 수 있다.

x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [15]:
# 아래와 같이 numpy ndarray나 python의 list도 tensor로 바꿀 수 있다.
x_np = np.array([[1.0, 2.0],
                 [3.0, 4.0]])
x_list = [[1.0, 2.0],
          [3.0, 4.0]]

print(type(x_np))
print(type(x_list))
print(x_np, x_np.shape, x_np.ndim)

<class 'numpy.ndarray'>
<class 'list'>
[[1. 2.]
 [3. 4.]] (2, 2) 2


In [17]:
x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(x_np, type(x_np))
print(x_list, type(x_list))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64) <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [20]:
# 반대로 tensor를 다음과 같이 Numpy ndarray로 바꿀 수 있다.
x.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [22]:
print(type(x.numpy()))

<class 'numpy.ndarray'>


In [26]:
a = tf.ones((2,3))
print(a)

b = np.ones((2,3))
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
a = tf.ones((2,3))
b = tf.zeros((2,3))
c = tf.fill((2,3), 2)

print(a, b, c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32) tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [31]:
# _like()를 하면 모양 뿐만 아니라 type까지 가져온다.
d = tf.zeros_like(c)
e = tf.ones_like(c)
print(d, e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32) tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [32]:
f = tf.eye(3)
print(f)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [33]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [34]:
h = tf.random.uniform((2,2)) # np.rand
i = tf.random.normal((2,2)) # np.randn

## Tensor의 속성

In [36]:
tensor = tf.random.normal((3,4))

print(f"shape fo tensor: {tensor.shape}")
print(f"datatype fo tensor: {tensor.dtype}")

shape fo tensor: (3, 4)
datatype fo tensor: <dtype: 'float32'>


In [37]:
tensor = tf.reshape(tensor, (4,3))
tensor = tf.cast(tensor, tf.int32)

print(f"shape fo tensor: {tensor.shape}")
print(f"datatype fo tensor: {tensor.dtype}")

shape fo tensor: (4, 3)
datatype fo tensor: <dtype: 'int32'>


### Variable
Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서이다.</br>
딥 러닝에서는 학습해야하는 가중치(weight, bias)를 variable로 생성한다.

In [43]:
# tensor의 값 변경 - 변경 불가능
tensor = tf.ones((3,4))
print(tensor)

tensor[0,0] = 2.

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [48]:
test = np.ones((3,4))
print(test)

test[0,0] = 2
print(test)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
# variable 만들기, 값 변경
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [50]:
# 초기값을 사용해서 Variable을 생성할 수 있다.
initial_value = tf.random.normal(shape = (2,2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.20620306, -0.75076514],
       [-1.1637049 ,  0.05804265]], dtype=float32)>


In [51]:
weight[0,0].assign(2)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 2.        , -0.75076514],
       [-1.1637049 ,  0.05804265]], dtype=float32)>


In [54]:
# 아래와 같이 variable을 초기화해주는 initializer를 사용할 수 있다.
weight = tf.Variable(tf.random_normal_initializer(stddev=1.)(shape=(2,2)))
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.03770087, -0.54099184],
       [-0.9948532 ,  0.86480314]], dtype=float32)>


In [55]:
# variabl은 .assing(value), .assign_add(increment), assign_sub(decrement)를 이용해 값을 갱신한다.
new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

tf.Tensor(
[[-0.37631673 -0.2799352 ]
 [ 0.9516725  -0.6419305 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.37631673, -0.2799352 ],
       [ 0.9516725 , -0.6419305 ]], dtype=float32)>


In [56]:
add_value = tf.ones(shape=(2,2))
weight.assign_sub(add_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.3763168 , -1.2799352 ],
       [-0.04832751, -1.6419306 ]], dtype=float32)>


In [58]:
print(add_value)
weight.assign_add(add_value)
print(weight)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.6236832 , 0.72006476],
       [1.9516726 , 0.35806942]], dtype=float32)>


### indexing과 slicing

In [59]:
a = tf.range(1, 13)
a = tf.reshape(a, (3,4))
print(a)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [73]:
# indexing
print(a[1])
print(a[0,-1])
print(a[...,0])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 5 9], shape=(3,), dtype=int32)


In [75]:
# slicing
print(a[1:-1])
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


### Transpose

In [78]:
a = tf.range(16)
a = tf.reshape(a, (2, 2, -1))
print(a)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [79]:
b = tf.transpose(a, (2, 0, 1))
print(b)

tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)
