In [ ]:
import numpy as np

In [ ]:
my_arr = np.arange(1000000)

In [ ]:
my_list = list(range(100))

In [ ]:
%timeit my_arr2 = my_arr *2

In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

In [ ]:
print(my_arr)

In [ ]:
print(my_list)

### 4.1 다차원 배열 객체 ndarray
- 넘파이는 대규모 데이터셋을 담을 수 있는 빠르고 유연한 자료 구조다.

In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [ ]:
data

In [ ]:
data * 10

In [ ]:
data + data

In [ ]:
data.shape

In [ ]:
data.dtype

#### 4.1.1 ndarray 생성하기

In [ ]:
data1 = [6, 7.5, 8, 0, 1]

In [ ]:
arr1 = np.array(data1)

In [ ]:
arr1

In [ ]:
data1

- 리스트 길이가 동일한 중첩된 순차 데이터는 다차원 배열로 변환 가능하다

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr2 = np.array(data2)

In [ ]:
arr2

- data2는 리스트를 담고 있는 리스트이므로 넘파이 배열인 arr2는 해당 데이터로부터 형태를 추론해 2차원 형태로 생성된다.

In [ ]:
arr2.ndim

In [ ]:
arr2.shape

In [ ]:
arr1.dtype

In [ ]:
arr2.dtype

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((3,6))

In [ ]:
np.empty((2,3,2))

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr1.dtype
arr2.dtype

print(arr1, arr2)

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.dtype 

In [ ]:
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

#### 4.1.2 숫자 형식의 문자열을 담고 있는 배열이 있다면 'astype'을 사용해 숫자로 변환할 수 있다.

In [ ]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.str_)

In [ ]:
numeric_strings

In [ ]:
numeric_strings.astype(float)

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

In [ ]:
arr

In [ ]:
arr * arr

In [ ]:
arr = [[1, 2, 3], [4, 5, 6]]
total_sum = 0

for row in arr:
    for element in row:
        total_sum += element

print("Total Sum:", total_sum)

In [ ]:
arr = [[1, 2, 3], [4, 5, 6]]
result = []

for row in arr:
    new_row = []
    for element in row:
        new_row.append(element * 2)
    result.append(new_row)

print("Result after multiplying by 2:", result)


#### 4.1.3 넘파이 배열의 산술 연산

In [ ]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])
arr2

In [ ]:
arr2 > arr

#### 4.1.4 색인과 슬라이싱 기초

In [ ]:
arr = np.arange(10)

In [ ]:
print([arr[5], arr[5:8]])

In [ ]:
arr[5:8] = 12
arr

In [ ]:
arr_slice = arr[5:8]

In [ ]:
arr_slice

In [ ]:
arr_slice[1] = 12345

In [ ]:
arr_slice

In [ ]:
arr_copy = arr[5:8].copy()

In [ ]:
arr_copy

In [ ]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
arr2d

In [ ]:
arr2d[1, :2]

In [ ]:
arr2d[:, 0]

In [ ]:
arr2d[:, :1]

In [ ]:
arr = np.zeros((8,4))

In [ ]:
for i in range(8):
    arr[i] = i

In [ ]:
arr

In [ ]:
arr[[4,3,0,6]]

In [ ]:
arr = np.arange(32).reshape((8,4))

In [73]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [76]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

## 4.2 난수 생성

In [1]:
import numpy as np

In [2]:
# 표준정규분포 난수 생성
samples = np.random.standard_normal(size = (4,4))

In [3]:
samples

array([[-0.09188921,  0.40574723,  0.0054088 ,  0.13926003],
       [ 0.70427561, -1.46969075, -0.6028143 , -0.95188781],
       [-0.55847324,  1.65700137, -1.17836843,  0.12859294],
       [-0.43664928, -1.86050319,  0.26346239,  1.58865492]])

In [4]:
from random import normalvariate

In [5]:
N = 1000000

In [6]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

967 ms ± 281 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%timeit np.random.standard_normal(N)

36.6 ms ± 335 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
rng = np.random.default_rng(seed = 1234)
data = rng.standard_normal((2,3))

In [16]:
type(rng)

numpy.random._generator.Generator

In [17]:
data

array([[-1.60383681,  0.06409991,  0.7408913 ],
       [ 0.15261919,  0.86374389,  2.91309922]])

In [18]:
rng

Generator(PCG64) at 0x1179CD700

## 4.3 유니버셜함수: 배열의 각 원소를 빠르게 처리하는 함수

In [11]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [20]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

In [21]:
x

array([-1.26514372, -2.15913901,  0.43473395,  1.73328932,  0.52013416,
       -1.00216579,  0.26834554,  0.7671747 ])

In [22]:
y

array([ 1.19127203, -1.15741081,  0.6962794 ,  0.35138369, -0.03241508,
        0.01318158, -0.67924997, -0.62053203])