In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
data = [1, 2, 3]
arry = np.array(data)
print(arry)
print(type(arry))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
result = []
for i in data:
    a = i * 10
    result.append(a)

print(result)

[10, 20, 30]


In [4]:
arry

array([1, 2, 3])

In [5]:
arry * 10

array([10, 20, 30])

In [7]:
print(arry)

[1 2 3]


In [6]:
data2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(data2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
data2d[0]

[1, 2, 3]

In [8]:
data2d[1]

[4, 5, 6]

In [9]:
type(data2d)

list

In [10]:
arry = np.array(data2d)
print(arry[:, 0])

[1 4 7]


## page 27
numpy는 다차원 배열을 위한 ndarray클래스(타입)를 제공한다.</br>
1차원 리스트를 Numpy array 함수에 전달하면 쉽게 ndarray객체로 변환할 수 있다.</br>
범용적인 용도로 사용되는 파이썬 list 타입을 행렬과 다차원 배열에 최적화된 ndarray타입으로 변환하는 것이다.

In [13]:
data1 = [1, 2, 3, 4]

arr1 = np.array(data1)

In [14]:
print(arr1)

[1 2 3 4]


In [16]:
print(type(arr1))

<class 'numpy.ndarray'>


In [17]:
data2 = [
    [1, 2],
    [3, 4]
]

arr2 = np.array(data2)

In [21]:
print(arr2[0])

[1 2]


In [22]:
print(arr2[1])

[3 4]


In [20]:
print(type(arr2[0]))

<class 'numpy.ndarray'>


ndarray 객체의 인스턴스 변수를 사용해서 저장된 데이터의 정보를 조회할 수 있다.</br>
shape는 ndarray의 크기 정보를, ndim은 차원 정보를, dtype은 데이터 타입을 표현한다.

In [23]:
print(arr2.shape)

(2, 2)


In [24]:
print(arr2.ndim)

2


In [25]:
print(arr2.dtype)

int64


In [26]:
print(arr1.shape)

(4,)


튜플에 하나의 값이 들어 있을 때는 1차원 데이터를 뜻하며, 첫 번째 값이 로우의 길이가 아닌 데이터의 길이다.

In [28]:
print(np.zeros(3))

[0. 0. 0.]


In [29]:
print(np.ones(3))

[1. 1. 1.]


zeros와 ones 함수는 기본적으로 float타입으로 데이터를 저장한다.</br>
출력된 결과에 소수점(dot)은 저장된 데이터가 float타입임을 알려준다.

In [30]:
size = (3, 4)

In [31]:
type(size)

tuple

In [32]:
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [34]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2, 3)
print(ndarr2)

[[0 1 2]
 [3 4 5]]


In [35]:
ndarr1.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
arr = np.array([1, 2, 3], dtype = np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [37]:
arr = arr.astype('int8')
print(arr.dtype)

int8


In [40]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


In [41]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [43]:
a16 = np.array([1.0], dtype = np.float16)
a32 = np.array([1.0], dtype = np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


## 인덱싱과 슬라이싱

In [8]:
arr = np.arange(4).reshape(2, 2)

In [9]:
print(arr[0])

[0 1]


In [10]:
print(arr[0][0])

0


In [11]:
print(arr[0, 0])

0


In [13]:
a = np.arange(10000).reshape(100, 100)

In [15]:
%timeit a[0, 50]

125 ns ± 2.49 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [16]:
a = np.arange(10000).reshape(100, 100)
%timeit a[0][50]

240 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
arr = np.arange(4)

In [22]:
print(arr[ : 4])

[0 1 2 3]


In [24]:
arr = np.arange(8).reshape(4,2)

In [25]:
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [27]:
print(arr[ :2])

[[0 1]
 [2 3]]


In [31]:
target = [0,2]

In [32]:
print(arr[ target ])

[[0 1]
 [4 5]]


In [33]:
print(arr[[0, 2]])

[[0 1]
 [4 5]]


In [35]:
arr = np.arange(20).reshape(4, 5)
print(arr[ : 2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
arr[ : 2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
result = []
for i in arr:
    row01 = [ i[0], i[1]]
    result.append(row01)

In [39]:
result

[[0, 1], [5, 6], [10, 11], [15, 16]]

In [40]:
arr[ :, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [41]:
arr[ :2, :2]

array([[0, 1],
       [5, 6]])

In [51]:
arr[2:3, 3:4]

array([[13]])

## 브로드캐스팅

In [52]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a + b)
print(a * b)
print(a % b)

[3 5 7]
[ 2  6 12]
[1 2 3]


In [53]:
print(a + 3)

[4 5 6]


In [54]:
c = np.arange(2)

In [55]:
d = np.arange(6).reshape(3, 2)

In [60]:
print( c + d)

[[0 2]
 [2 4]
 [4 6]]


In [59]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [62]:
e = np.arange(3).reshape(3,1)

In [63]:
e

array([[0],
       [1],
       [2]])

In [64]:
e + d

array([[0, 1],
       [3, 4],
       [6, 7]])

In [65]:
e + d

array([[0, 1],
       [3, 4],
       [6, 7]])

In [69]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

In [70]:
arr_diff = arr_high - arr_low

In [71]:
print(arr_diff)

[2700 1300  400 2200 1400]


In [2]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]

In [3]:
arr = np.array(data)

In [4]:
arr

array([[92700, 92400, 92100, 94300, 92300],
       [90000, 91100, 91700, 92100, 90900]])

In [5]:
arr[0]*3 + arr[1]*2

array([458100, 459400, 459700, 467100, 458700])

In [6]:
weight = np.array([3,2]).reshape(2, 1)

In [7]:
weight

array([[3],
       [2]])

In [8]:
(weight*arr).sum(axis=0)

array([458100, 459400, 459700, 467100, 458700])

In [9]:
(weight*arr).sum(axis=1)

array([1391400,  911600])

## 조건연산

In [11]:
arr = np.array([10, 20, 30])
print(arr > 10)

[False  True  True]


In [15]:
arr = np.array([10, 20, 30])
cond = [True, False, True]
print(arr[ cond ])

[10 30]


In [16]:
arr = np.array([10, 20, 30])
cond = arr > 10

In [17]:
cond

array([False,  True,  True])

In [18]:
print(arr[cond])

[20 30]


In [20]:
print(arr[arr > 10])

[20 30]


In [21]:
cond.all()

False

In [22]:
cond.any()

True

In [23]:
arr = np.array([10, 20, 30])

In [24]:
cond0 = arr > 10

In [25]:
cond1 = arr < 30

In [26]:
print(arr[cond0 & cond1])

[20]


In [28]:
print(arr[(arr > 10) & (arr < 30)])

[20]


In [29]:
arr = np.array([10, 20, 30])

In [30]:
cond = arr > 10

In [31]:
arr[cond] = 1

In [32]:
arr[~cond] = 0

In [33]:
cond

array([False,  True,  True])

In [34]:
arr

array([0, 1, 1])

In [35]:
arr = np.array([10, 20, 30])

In [36]:
arr = np.where(arr > 10, 1, 0)

In [37]:
print(arr)

[0 1 1]


In [38]:
arr = np.array([10, 20, 30])

In [39]:
arr = np.where(arr >10, arr + 10, arr - 10)

In [40]:
print(arr)

[ 0 30 40]


## 함수와 메서드

In [41]:
arr = np.arange(8).reshape(4,2)

In [42]:
print(arr.sum())

28


In [43]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [44]:
print(arr.sum(axis=0))

[12 16]


In [45]:
print(arr.sum(axis=1))

[ 1  5  9 13]


In [46]:
np.random.randint(3)

2

In [47]:
np.random.randint(456, size = 5)

array([410, 320, 365,  18, 203])

In [48]:
np.random.randint(46, size = (2, 5))

array([[33, 14, 14, 32, 35],
       [40, 23, 38, 32, 39]])

In [49]:
x = np.linspace(0, 10, 3)

In [50]:
x

array([ 0.,  5., 10.])

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
b = np.arange(4, 8)

In [4]:
c = np.vstack([a,b])

In [5]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
d = np.random.randint(400, size = 4)

In [7]:
d

array([320, 113,  88, 313])

In [8]:
np.vstack([a,d])

array([[  0,   1,   2,   3],
       [320, 113,  88, 313]])