In [1]:
import numpy as np

In [3]:
data = [1, 2, 3]
arry = np.array(data)
print(arry)
print(type(arry))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
result = []
for i in data:
    a = i * 10
    result.append(a)

print(result)

[10, 20, 30]


In [5]:
arry

array([1, 2, 3])

In [6]:
arry * 10

array([10, 20, 30])

In [7]:
data2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(data2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
data2d[0]

[1, 2, 3]

In [9]:
data2d[1]

[4, 5, 6]

In [10]:
type(data2d)

list

In [12]:
arry = np.array(data2d)
print(arry[:, 0])

[1 4 7]


In [16]:
arry([:2, ])

SyntaxError: invalid syntax (3524024334.py, line 1)

### page 27