In [1]:
import numpy as np

In [2]:
data = [1, 2, 3]
arry = np.array(data)
print(arry)
print(type(arry))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
result = []
for i in data:
    a = i * 10
    result.append(a)

print(result)

[10, 20, 30]


In [4]:
arry

array([1, 2, 3])

In [5]:
arry * 10

array([10, 20, 30])

In [6]:
data2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(data2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
data2d[0]

[1, 2, 3]

In [8]:
data2d[1]

[4, 5, 6]

In [9]:
type(data2d)

list

In [10]:
arry = np.array(data2d)
print(arry[:, 0])

[1 4 7]


### page 27
numpy는 다차원 배열을 위한 ndarray클래스(타입)를 제공한다.</br>
1차원 리스트를 Numpy array 함수에 전달하면 쉽게 ndarray객체로 변환할 수 있다.</br>
범용적인 용도로 사용되는 파이썬 list 타입을 행렬과 다차원 배열에 최적화된 ndarray타입으로 변환하는 것이다.

In [13]:
data1 = [1, 2, 3, 4]

arr1 = np.array(data1)

In [14]:
print(arr1)

[1 2 3 4]


In [16]:
print(type(arr1))

<class 'numpy.ndarray'>


In [17]:
data2 = [
    [1, 2],
    [3, 4]
]

arr2 = np.array(data2)

In [21]:
print(arr2[0])

[1 2]


In [22]:
print(arr2[1])

[3 4]


In [20]:
print(type(arr2[0]))

<class 'numpy.ndarray'>


ndarray 객체의 인스턴스 변수를 사용해서 저장된 데이터의 정보를 조회할 수 있다.</br>
shape는 ndarray의 크기 정보를, ndim은 차원 정보를, dtype은 데이터 타입을 표현한다.

In [23]:
print(arr2.shape)

(2, 2)


In [24]:
print(arr2.ndim)

2


In [25]:
print(arr2.dtype)

int64


In [26]:
print(arr1.shape)

(4,)


튜플에 하나의 값이 들어 있을 때는 1차원 데이터를 뜻하며, 첫 번째 값이 로우의 길이가 아닌 데이터의 길이다.

In [28]:
print(np.zeros(3))

[0. 0. 0.]


In [29]:
print(np.ones(3))

[1. 1. 1.]


zeros와 ones 함수는 기본적으로 float타입으로 데이터를 저장한다.</br>
출력된 결과에 소수점(dot)은 저장된 데이터가 float타입임을 알려준다.

In [30]:
size = (3, 4)

In [31]:
type(size)

tuple

In [32]:
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [34]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2, 3)
print(ndarr2)

[[0 1 2]
 [3 4 5]]


In [35]:
ndarr1.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
arr = np.array([1, 2, 3], dtype = np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [37]:
arr = arr.astype('int8')
print(arr.dtype)

int8


In [40]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


In [41]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [43]:
a16 = np.array([1.0], dtype = np.float16)
a32 = np.array([1.0], dtype = np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


## 인덱싱과 슬라이싱